# Generated by Django 5.1.4 on 2025-02-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usertestmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTestModel',
            new_name='Users',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
    ]
