# Generated by Django 5.1.4 on 2025-02-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='profile_picture',
            field=models.ImageField(default='blank_profile_pic.jpg', upload_to='profile_pics'),
        ),
    ]
