# Generated by Django 5.1.4 on 2025-02-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profilepicture_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='profile_picture',
            field=models.ImageField(default='/media/blank_profile_pic.jpg', upload_to='media/profile_pics/'),
        ),
    ]
