# Generated by Django 5.1.4 on 2025-02-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profilepicture_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='profile_picture',
            field=models.ImageField(upload_to='media/profile_pics/'),
        ),
    ]
