# Generated by Django 5.1.4 on 2025-02-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_contact_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Enquiry',
        ),
    ]
