# Generated by Django 5.1.4 on 2025-02-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_contact_enquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='enquire_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='enquire_fname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='enquire_lname',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='enquiry_text',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='enquiry_select',
            new_name='select',
        ),
    ]
