# Generated by Django 5.1.4 on 2025-02-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_enquire_email_enquiry_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
