# Generated by Django 5.1.4 on 2025-02-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_text', models.CharField(max_length=500)),
                ('enquiry_select', models.CharField(max_length=100)),
                ('enquire_fname', models.CharField(max_length=20)),
                ('enquire_lname', models.CharField(max_length=20)),
                ('enquire_email', models.CharField(max_length=30)),
            ],
        ),
    ]
